2020-07-27 15:22:50,130 ERROR: Exception on /user/Jason [GET] [in /Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sherry/Desktop/mircoblog/app/routes.py", line 57, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/sherry/Desktop/mircoblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/sherry/Desktop/mircoblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/sherry/Desktop/mircoblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/sherry/Desktop/mircoblog/app/templates/user.html", line 33, in block "app_content"
    {% include '_post.html' %}
  File "/Users/sherry/Desktop/mircoblog/app/templates/_post.html", line 12, in top-level template code
    said {{ moment(post.timestamp).fromNow() }}:
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_moment.py", line 157, in fromNow
    refresh=refresh)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_moment.py", line 139, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_moment.py", line 135, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'timestamp'
2020-07-27 15:23:03,772 ERROR: Exception on /user/susan [GET] [in /Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sherry/Desktop/mircoblog/app/routes.py", line 57, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/sherry/Desktop/mircoblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/sherry/Desktop/mircoblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/sherry/Desktop/mircoblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/sherry/Desktop/mircoblog/app/templates/user.html", line 33, in block "app_content"
    {% include '_post.html' %}
  File "/Users/sherry/Desktop/mircoblog/app/templates/_post.html", line 12, in top-level template code
    said {{ moment(post.timestamp).fromNow() }}:
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_moment.py", line 157, in fromNow
    refresh=refresh)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_moment.py", line 139, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/Users/sherry/Desktop/mircoblog/venv/lib/python3.7/site-packages/flask_moment.py", line 135, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'timestamp'
2020-07-27 15:24:19,921 INFO: Microblog startup [in /Users/sherry/Desktop/mircoblog/app/__init__.py:47]
2020-07-27 15:25:31,712 INFO: Microblog startup [in /Users/sherry/Desktop/mircoblog/app/__init__.py:47]
2020-07-27 15:26:35,973 INFO: Microblog startup [in /Users/sherry/Desktop/mircoblog/app/__init__.py:47]
2020-07-27 15:27:32,844 INFO: Microblog startup [in /Users/sherry/Desktop/mircoblog/app/__init__.py:47]
